export const TopIndustries = [
 {'name' : 'all', 'count': 47000},
 {'name':'e-commerce','count':5061},
 {'name':'mobile', 'count': 4724},
 {'name':'enterprise software','count':2609},
 {'name':'healthcare','count':2342},
 {'name':'marketing','count':2235},
 {'name':'finance','count':1944},
 {'name':'advertising','count':1649},
 {'name':'media','count':1601},
 {'name':'gaming','count':1413},
 {'name':'analytics','count':1352},
 {'name':'education','count':1322},
 {'name':'entertainment','count':1301},
 {'name':'software development','count':1136},
 {'name':'hardware','count':1089},
 {'name':'social networking','count':940},
 {'name':'biotechnology','count':732},
 {'name':'security','count':719},
 {'name':'real estate','count':717},
 {'name':'music','count':702},
 {'name':'pharmaceuticals','count':695},
 {'name':'cloud computing','count':630},
 {'name':'fashion','count':616},
 {'name':'cleantech','count':587}
];